name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: ubuntu-latest

 steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 准备环境
        run: |
          sudo apt-get update
          sudo apt install -y ack antlr3 asciidoc autoconf automake autopoint binutils bison build-essential bzip2 ccache cmake cpio curl device-tree-compiler fastjar flex gawk gettext gcc-multilib g++-multilib git gperf haveged help2man intltool libc6-dev-i386 libelf-dev libfuse-dev libglib2.0-dev libgmp3-dev libltdl-dev libmpc-dev libmpfr-dev libncurses5-dev libncursesw5-dev libpython3-dev libreadline-dev libssl-dev libtool lrzsz mkisofs msmtp ninja-build p7zip p7zip-full patch pkgconf python2.7 python3 python3-pyelftools python3-setuptools qemu-utils rsync scons squashfs-tools subversion swig texinfo uglifyjs upx-ucl unzip vim wget xmlto xxd zlib1g-dev

      - name: Clone build repository
        run: |
          cd ImmortalWrt
          ./scripts/feeds update -a
          ./scripts/feeds install -a
          
      - name: Compile the firmware
        run: |
          cd ImmortalWrt
          make -j8 V=s
          
      - name: Upload Firmware
        uses: actions/upload-artifact@v4
        with:
          name: immortalwrt-images
          path: ImmortalWrt
